language: ruby
rvm:
  - 2.2.3
before_install:
  - gem update --system
  - rvm @global do gem uninstall -ax bundler
  - gem uninstall -ax bundler
  - gem install bundler -v 1.10.5
env:
  global:
    - SPEC_OPTS="--tag ~skip_travis"
  matrix:
    - VAGRANT_VERSION=v1.8.1
matrix:
  include:
    - env: VAGRANT_VERSION=master
      rvm: 2.2.3
    - env: VAGRANT_VERSION=v1.7.4
      rvm: 2.0.0
  allow_failures:
    - env: VAGRANT_VERSION=master
      rvm: 2.2.3
sudo: false
